/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.crest.dlt.ui.main;

import java.awt.Color;
import java.util.logging.Logger;

import javax.swing.UIManager;

import org.apache.commons.cli.ParseException;

import edu.crest.dlt.ui.utils.CommandLineOptionParser;
import edu.crest.dlt.utils.Configuration;

/**
 * @author Rohit
 */
public class UploadDownloadFrame extends javax.swing.JFrame
{
	private static final Logger log = Logger.getLogger(UploadDownloadFrame.class.getName());

	/**
	 * Creates new form UploadDownloadFrame
	 */
	public UploadDownloadFrame()
	{
		setTitle(Configuration.dlt_ui_title);

		initComponents();
		setLocationRelativeTo(null); // for centering
		log.info("started application. (says \"hola\" ^_^)");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadPanel1 = new edu.crest.dlt.ui.up.UploadPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_download = new edu.crest.dlt.ui.down.DownloadPanel();
        uploadPanel2 = new edu.crest.dlt.ui.up.UploadPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Download", panel_download);
        jTabbedPane1.addTab("Upload", uploadPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	public static void loadCommandLineConfiguration(String args[]) throws ParseException
	{
		CommandLineOptionParser parser = new CommandLineOptionParser(args);
		Configuration.dlt_username = parser.getUsername();
		log.info("Username      : " + Configuration.dlt_username);

		Configuration.dlt_password = parser.getPassword();
		log.info("Password      : " + Configuration.dlt_password);

		Configuration.dlt_file_paths = parser.getFiles();
		log.info("Files         : " + Configuration.dlt_file_paths.toString());

		Configuration.dlt_exnode_transfer_size_default = parser.getTransferSize();
		log.info("Transfer Size : " + parser.getTransferSize());

		Configuration.dlt_exnode_transfer_connections_default = parser.getNumOfConnections();
		log.info("Threads       : " + parser.getNumOfConnections());
	}

	/**
	 * @param args
	 *          the command line arguments
	 * @throws ParseException 
	 */
	public static void main(String args[]) throws ParseException
	{
		Configuration.load();
		loadCommandLineConfiguration(args);
		
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(UploadDownloadFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(UploadDownloadFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(UploadDownloadFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(UploadDownloadFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		
		UIManager.getLookAndFeelDefaults().put("List[Selected].textBackground", new Color(57, 105, 138));
	  UIManager.getLookAndFeelDefaults().put("List[Selected].textForeground", Color.WHITE);

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new UploadDownloadFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private edu.crest.dlt.ui.down.DownloadPanel panel_download;
    private edu.crest.dlt.ui.up.UploadPanel uploadPanel1;
    private edu.crest.dlt.ui.up.UploadPanel uploadPanel2;
    // End of variables declaration//GEN-END:variables
}
