/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.crest.dlt.ui.down;

import javax.swing.JFileChooser;

import edu.crest.dlt.ui.utils.img.Icons;

/**
 * @author Rohit
 */
public class DirectoryChooserPanel extends javax.swing.JPanel
{

	/**
	 * Creates new form OutputDirectoryPanel
	 */
	public DirectoryChooserPanel()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    input_directory = new javax.swing.JLabel();
    button_browse_directory = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output Directory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    setPreferredSize(new java.awt.Dimension(500, 47));

    input_directory.setText(System.getProperty("user.home"));

    button_browse_directory.setIcon(Icons.icon_directory_empty);
    button_browse_directory.setText("Browse");
    button_browse_directory.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        button_browse_directory_clicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(input_directory, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(button_browse_directory))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(input_directory, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(button_browse_directory))
    );
  }// </editor-fold>//GEN-END:initComponents

	private void button_browse_directory_clicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_button_browse_output_directory_clicked
		JFileChooser chooser = new JFileChooser();
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		int result = chooser.showOpenDialog(null);

		if (result == JFileChooser.APPROVE_OPTION) {
			input_directory.setText(chooser.getSelectedFile().getPath());
		}
	}// GEN-LAST:event_button_browse_output_directory_clicked

	public String directory()
	{
		return input_directory.getText();
	}
	
	public void directory(String output_directory)
	{
		input_directory.setText(output_directory);
	}
	
	public void disable() {
		button_browse_directory.setEnabled(false);
	}
	
	public void enable() {
		button_browse_directory.setEnabled(true);
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button_browse_directory;
  private javax.swing.JLabel input_directory;
  // End of variables declaration//GEN-END:variables
}
